# fly.toml app configuration file generated for panic on 2024-10-01T21:18:23+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'panic'
primary_region = 'syd'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
DATABASE_PATH = '/mnt/panic_data/panic_data.db'
PHX_HOST = 'panic.fly.dev'
PORT = '8080'

[[mounts]]
source = 'panic_data'
destination = '/mnt/panic_data'
processes = ['app']
initial_size = '5gb'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2
