project_name: "panic"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done", "Thought Bubbles"]
labels: []
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
backlog_directory: "backlog"
auto_open_browser: true
default_port: 6420
remote_operations: false # makes things speedier, and for a solo dev is fine
auto_commit: false
