defmodule Panic.Repo.Migrations.RemoveNetworkState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:networks) do
      remove :state
    end
  end

  def down do
    alter table(:networks) do
      add :state, :text, null: false
    end
  end
end
