defmodule Panic.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:api_tokens, [:name, :value], name: "api_tokens_token_index")

    create unique_index(:api_tokens, [:name, :user_id], name: "api_tokens_token_index")
  end

  def down do
    drop_if_exists unique_index(:api_tokens, [:name, :user_id], name: "api_tokens_token_index")

    create unique_index(:api_tokens, [:name, :value], name: "api_tokens_token_index")
  end
end