defmodule Panic.Repo.Migrations.AddApiTokensMap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :api_tokens, :map, default: %{}
    end
  end

  def down do
    alter table(:users) do
      remove :api_tokens
    end
  end
end