defmodule Panic.Repo.Migrations.AddModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:networks) do
      add :models, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:networks) do
      remove :models
    end
  end
end