defmodule Panic.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invocations, primary_key: false) do
      add :network_id,
          references(:networks, column: :id, name: "invocations_network_id_fkey", type: :bigint),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :run_number, :bigint
      add :sequence_number, :bigint, null: false
      add :output, :text
      add :model, :text
      add :input, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:invocations, "invocations_network_id_fkey")

    drop table(:invocations)
  end
end