defmodule Panic.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:users) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :api_tokens
    # end
    # 
    create table(:api_tokens, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "api_tokens_user_id_fkey", type: :bigint),
          null: false

      add :value, :text, null: false
      add :name, :text, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:api_tokens, "api_tokens_user_id_fkey")

    drop table(:api_tokens)

    # alter table(:users) do
    # This is the `down` migration of the statement:
    #
    #     remove :api_tokens
    #
    # 
    # add :api_tokens, :map, default: %{}
    # end
    # 
  end
end