defmodule Panic.Repo.Migrations.InitialMigrationButNotReally do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:networks, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :slug, :text
      add :state, :text, null: false
      add :models, {:array, :text}, null: false, default: []
      add :description, :text
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:models, primary_key: false) do
      add :network_id,
          references(:networks, column: :id, name: "models_network_id_fkey", type: :bigint),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :run_number, :bigint
      add :sequence_number, :bigint, null: false
      add :output, :text
      add :model, :text
      add :input, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:models, "models_network_id_fkey")

    drop table(:models)

    drop table(:networks)
  end
end