defmodule Panic.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:networks, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :slug, :text
      add :state, :text, null: false
      add :description, :text
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop table(:networks)
  end
end