defmodule Panic.Repo.Migrations.CreateApiTokensAndJoinTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_api_tokens, primary_key: false) do
      add :api_token_id,
          references(:api_tokens,
            column: :id,
            name: "user_api_tokens_api_token_id_fkey",
            type: :bigint
          ),
          null: false

      add :user_id,
          references(:users, column: :id, name: "user_api_tokens_user_id_fkey", type: :bigint),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:api_tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :allow_anonymous_use, :boolean
      add :vestaboard_panic_4_token, :text
      add :vestaboard_panic_3_token, :text
      add :vestaboard_panic_2_token, :text
      add :vestaboard_panic_1_token, :text
      add :gemini_token, :text
      add :openai_token, :text
      add :replicate_token, :text
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop table(:api_tokens)

    drop constraint(:user_api_tokens, "user_api_tokens_user_id_fkey")

    drop constraint(:user_api_tokens, "user_api_tokens_api_token_id_fkey")

    drop table(:user_api_tokens)
  end
end
