defmodule Panic.Repo.Migrations.AddAdminToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      # Add admin field with a default value of false for existing records
      add :admin, :boolean, null: false, default: false
    end

    # alter table(:api_tokens) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :allow_anonymous_use
    # end
    # 
  end

  def down do
    # alter table(:api_tokens) do
    # This is the `down` migration of the statement:
    #
    #     remove :allow_anonymous_use
    #
    # 
    # add :allow_anonymous_use, :boolean
    # end
    # 
    alter table(:users) do
      remove :admin
      # This is the `down` migration of the statement:
      #
      #     remove :replicate_token
      #

      # add :replicate_token, :text
      # This is the `down` migration of the statement:
      #
      #     remove :openai_token
      #

      # add :openai_token, :text
      # This is the `down` migration of the statement:
      #
      #     remove :gemini_token
      #

      # add :gemini_token, :text
      # This is the `down` migration of the statement:
      #
      #     remove :vestaboard_panic_1_token
      #

      # add :vestaboard_panic_1_token, :text
      # This is the `down` migration of the statement:
      #
      #     remove :vestaboard_panic_2_token
      #

      # add :vestaboard_panic_2_token, :text
      # This is the `down` migration of the statement:
      #
      #     remove :vestaboard_panic_3_token
      #

      # add :vestaboard_panic_3_token, :text
      # This is the `down` migration of the statement:
      #
      #     remove :vestaboard_panic_4_token
      #

      # add :vestaboard_panic_4_token, :text
    end
  end
end
