defmodule Panic.Repo.Migrations.AddLockoutSecondsToNetworks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:networks) do
      add :lockout_seconds, :bigint, null: false, default: 30
    end
  end

  def down do
    alter table(:networks) do
      remove :lockout_seconds
    end
  end
end
