defmodule Panic.Repo.Migrations.AddInstallations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:installations, primary_key: false) do
      add :network_id,
          references(:networks, column: :id, name: "installations_network_id_fkey", type: :bigint),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :watchers, {:array, :map}, null: false, default: []
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:installations, "installations_network_id_fkey")

    drop table(:installations)
  end
end