defmodule Panic.Repo.Migrations.DropNetworkSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:networks) do
      remove :slug
    end
  end

  def down do
    alter table(:networks) do
      add :slug, :text
    end
  end
end
